version: "2.2"
services:

  ui:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/ui:${KO_TAG}
    container_name: kubeoperator_ui
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/server:${KO_TAG}
    container_name: kubeoperator_server
    volumes:
      - ./conf/app.yaml:/etc/ko/app.yaml
    restart: always
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep","ko-server"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  kobe:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kobe:${KO_TAG}
    volumes:
      - ./data/kobe:/var/kobe/data
    container_name: kubeoperator_kobe
    healthcheck:
      test: ["CMD","kobe-inventory"]
      interval: 5s
      timeout: 3s
      retries: 10

  kotf:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kotf:${KO_TAG}
    container_name: kubeoperator_kotf
    volumes:
      - ./data/kotf:/var/kotf/data
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep","kotf-server"]
      interval: 5s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: kubeoperator_nginx
    restart: always
    ports:
      - ${KO_PORT}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql/mysql-server:8.0.21-amd64
    container_name: kubeoperator_mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - ./conf/mysql.env
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql

  grafana:
    image: grafana/grafana:7.1.0
    container_name: kubeoperator_grafana
    env_file:
      - ./conf/grafana.env
    volumes:
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep", "grafana-server"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  webkubectl:
    image: kubeoperator/webkubectl:v2.5.0
    container_name: kubeoperator_webkubectl
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD","curl","localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10

  nexus:
    restart: always
    image: docker.io/sonatype/nexus3:3.25.0
    container_name: kubeoperator_nexus
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./data/nexus-data/:/nexus-data